# Generated by Django 4.0 on 2022-01-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_newemployee'),
    ]

    operations = [
        migrations.CreateModel(
            name='advanceForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eno', models.IntegerField()),
                ('ename', models.CharField(max_length=30)),
                ('erole', models.CharField(max_length=25)),
                ('edate', models.CharField(max_length=20)),
                ('eadvance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='salaryForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eno', models.IntegerField()),
                ('ename', models.CharField(max_length=30)),
                ('emonth', models.CharField(max_length=15)),
                ('edate', models.CharField(max_length=150)),
                ('erole', models.CharField(max_length=40)),
                ('ebasic', models.FloatField()),
                ('epf', models.FloatField()),
                ('eadvance', models.FloatField()),
                ('enet', models.FloatField()),
            ],
        ),
    ]
