# Generated by Django 4.0 on 2022-01-16 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_advanceform_salaryform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='salaryForm',
        ),
    ]
